# Generated by Django 3.2 on 2024-09-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fono',
            field=models.CharField(max_length=15),
        ),
    ]
